version: '3.8'
services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
