version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
